// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;
import 'package:firebase_core/firebase_core.dart';
import 'firebase_options.dart';
/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCK7_z9ywQ7R5R9jbDa1HEJZrWmUdMiNjU',
    appId: '1:597477775559:web:04f4d549bcc825c33b86e2',
    messagingSenderId: '597477775559',
    projectId: 'testpush-81958',
    authDomain: 'testpush-81958.firebaseapp.com',
    storageBucket: 'testpush-81958.appspot.com',
    measurementId: 'G-QDL622V6RQ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA4BSg_L-vkE254XpwVDN3WDb6H0vIXsWo',
    appId: '1:597477775559:android:000ef1e0679f30443b86e2',
    messagingSenderId: '597477775559',
    projectId: 'testpush-81958',
    storageBucket: 'testpush-81958.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyATIU3JeNN-52lPQR_UWXp7mq2Hn-yRAys',
    appId: '1:597477775559:ios:e184b0269eaf1f3f3b86e2',
    messagingSenderId: '597477775559',
    projectId: 'testpush-81958',
    storageBucket: 'testpush-81958.appspot.com',
    iosClientId: '597477775559-n22pks6jngaapkjsegocelm11m7qbpq7.apps.googleusercontent.com',
    iosBundleId: 'com.example.testfire',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyATIU3JeNN-52lPQR_UWXp7mq2Hn-yRAys',
    appId: '1:597477775559:ios:e184b0269eaf1f3f3b86e2',
    messagingSenderId: '597477775559',
    projectId: 'testpush-81958',
    storageBucket: 'testpush-81958.appspot.com',
    iosClientId: '597477775559-n22pks6jngaapkjsegocelm11m7qbpq7.apps.googleusercontent.com',
    iosBundleId: 'com.example.testfire',
  );
}
